# Game Settings
import math

RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROTATION = 0.002

FOV = math.pi / 3
HALF_FOV = FOV / 2
NO_RAYS = WIDTH // 2
HALF_NO_RAYS = NO_RAYS // 2
DELTA_ANGLE = FOV / NO_RAYS
MAX_DEPTH = 20

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

PLAYER_SIZE_SCALE = 60

FLOOR_COLOUR = (30, 30, 30)

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NO_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2