# Game Settings
import math

RES = WIDTH, HEIGHT = 1600, 900
FPS = 60

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROTATION = 0.002

FOV = math.pi / 3
HALF_FOV = FOV / 2
NO_RAYS = WIDTH // 2
HALF_NO_RAYS = NO_RAYS // 2
DELTA_ANGLE = FOV / NO_RAYS
MAX_DEPTH = 20